// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpagtcsvedjaheuwmpnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwYWd0Y3N2ZWRqYWhldXdtcG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTgzNTQsImV4cCI6MjA2MzI3NDM1NH0.4zMgss5HtYTAX50lq-dv2Kbfo8P0BbSV3h5LLCUSgB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);